abstract: simple blog code for valid (X)HTML
author: Mirko Westermeier, C<< <mail at memowe.de> >>
build_requires: 
  Test::Exception: 0
  Test::More: 0
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-SBC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
version: 0.14
